=== gsgowell1982/AutoIND-Pro/ind-compliance-ai/data/regulations/附件1-2：受控词汇文件包/cn-elements.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- 
    BSfileC11 cn-elements.xsd 
	元素名称描述定义文件的 Schema 文件

	Version 1.0 - 2021年9月1日
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd" />
  <xs:element name="element-properties">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="version" type="T_version" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="T_version">
    <xs:sequence>
      <xs:element name="element" type="T_element" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="number" type="xs:string" use="required" />
    <xs:attribute name="valid-from" type="xs:date" use="required" />
    <xs:attribute name="valid-to" type="xs:date" use="optional" />
  </xs:complexType>
  <xs:complexType name="T_element">
    <xs:sequence>
      <xs:element name="description" type="T_description" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="structureno" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="T_description">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="xml:lang" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== gsgowell1982/AutoIND-Pro/ind-compliance-ai/data/regulations/附件1-2：受控词汇文件包/node-extension-property_CN.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
	BSfileC10 node-extension-property_CN.xml
	扩展节点名称描述定义文件

	Version 1.0 - 2021年9月1日
-->
<element-properties xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cn-elements.xsd">
  <version number="1.0" valid-from="2021-9-1">
    <element name="node-extension" structureno="3.2.R.1">
      <description xml:lang="zh">3.2.R.1工艺验证</description>
    </element>
    <element name="node-extension" structureno="3.2.R.2">
      <description xml:lang="zh">3.2.R.2批记录</description>
    </element>
    <element name="node-extension" structureno="3.2.R.3">
      <description xml:lang="zh">3.2.R.3分析方法验证报告</description>
    </element>
    <element name="node-extension" structureno="3.2.R.4">
      <description xml:lang="zh">3.2.R.4稳定性图谱</description>
    </element>
    <element name="node-extension" structureno="3.2.R.5">
      <description xml:lang="zh">3.2.R.5可比性方案</description>
    </element>
    <element name="node-extension" structureno="3.2.R.6">
      <description xml:lang="zh">3.2.R.6其他</description>
    </element>
  </version>
</element-properties>
